name: tarea3salon
description: Explorador de salón con Clean Architecture
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # UI
  google_fonts: ^6.1.0
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/classroom.jpg
    - assets/images/furniture/mesa.jpg
    - assets/images/furniture/silla.jpg
    - assets/images/furniture/pizarron.jpg
    - assets/images/furniture/lampara.jpg